spring:
  application:
    name: entity-graph-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/entitygraphdemo?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/entitygraphdemo?useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=true:

server:
  port: 8082
  servlet:
    context-path: /entity-graph-demo

